name: log_viewer
description: A Flutter app that fetches and displays logs from the internet.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  http: ^1.1.2
  flutter_dotenv: ^5.1.0

  intl: ^0.19.0

  faker: ^2.1.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
  #module:
  # androidX: true
  # plugin:
  # platforms:
  #   ios:
  #     pluginClass: FlutterLogsAppPlugin
  #   android:
  #    package: com.example.flutter_logs_app
  #    pluginClass: FlutterLogsAppPlugin
